# Generated by Django 5.0.4 on 2024-05-07 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0026_alter_song_users_plays'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='favourite',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='picture',
            field=models.ImageField(default='picture/playlists/default.jpg', upload_to='picture/playlists/'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='picture/playlists/collection-default.jpg', upload_to='picture/playlists/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.collection')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.song')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='songs',
            field=models.ManyToManyField(through='playlists.SongCollection', to='library.song'),
        ),
    ]
